repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: '0.6.0'
  hooks:
   - id: nbqa-black
     additional_dependencies: [black==20.8b1]
     args: [--nbqa-mutate]
   - id: nbqa-isort
     additional_dependencies: [isort==5.7.0]
     args: [--nbqa-mutate, --profile=black]
   - id: nbqa-flake8
     additional_dependencies: [flake8==3.9.0]
- repo: https://github.com/psf/black
  rev: '20.8b1'
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.8.0'
  hooks:
    - id: isort
      args: [--profile, black]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.812'
  hooks:
  - id: mypy
- repo: https://github.com/pycqa/flake8
  rev: '3.9.0'
  hooks:
  - id: flake8
    args: 
      - "--max-line-length=99"
      - "--ignore=E203,W503"
      - "--statistics"
      - "--count"
      - "--per-file-ignores=*/__init__.py:F401"
      - "--exclude=.joblib_cache,"
